<?php

# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# If you customize your file layout, set $IP to the directory that contains
# the other MediaWiki files. It will be used as a base to locate files.
if( defined( 'MW_INSTALL_PATH' ) ) {
	$IP = MW_INSTALL_PATH;
} else {
	$IP = dirname( __FILE__ );
}

$path = array( $IP, "$IP/includes", "$IP/languages" );
set_include_path( implode( PATH_SEPARATOR, $path ) . PATH_SEPARATOR . get_include_path() );

require_once( "$IP/includes/DefaultSettings.php" );

# If PHP's memory limit is very low, some operations may fail.
ini_set( 'memory_limit', '20M' );

if ( $wgCommandLineMode ) {
	if ( isset( $_SERVER ) && array_key_exists( 'REQUEST_METHOD', $_SERVER ) ) {
		die( "This script must be run from the command line\n" );
	}
}
## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename         = "AdminDocs";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath       = "/adminDocs";
$wgScriptExtension  = ".php";

## UPO means: this is also a user preference option

$wgEnableEmail      = true;
$wgEnableUserEmail  = true; # UPO

$wgEmergencyContact = "ptmscout_admin@mit.edu";
$wgPasswordSender = "ptmscout_admin@mit.edu";

$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype           = "mysql";
$wgDBserver         = "localhost";
$wgDBname           = "adminDocs";
$wgDBuser           = "ptmscout_admin";
$wgDBpassword       = "ptm_db8!";

# MySQL specific settings
$wgDBprefix         = "";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = true;

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads       = false;
# $wgUseImageMagick = true;
# $wgImageMagickConvertCommand = "/usr/bin/convert";

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
# $wgHashedUploadDirectory = false;

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
$wgUseTeX           = false;

$wgLocalInterwiki   = strtolower( $wgSitename );

$wgLanguageCode = "en";

$wgSecretKey = "93d38717355d0bfe082c8333b532d37df8f73b5d05d200b0335a911b2ef6e89d";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook':
$wgDefaultSkin = 'monobook';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
# $wgEnableCreativeCommonsRdf = true;
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";
# $wgRightsCode = ""; # Not yet used

$wgDiff3 = "/usr/bin/diff3";

# Logo
$wgLogo = "http://ptmscout.mit.edu/images/logoWiki.jpg";


# When you make changes to this configuration file, this will make
# sure that cached pages are cleared.
$wgCacheEpoch = max( $wgCacheEpoch, gmdate( 'YmdHis', @filemtime( __FILE__ ) ) );

/**
 * Permission keys given to users in each group.
 * All users are implicitly in the '*' group including anonymous visitors;
 * logged-in users are all implicitly in the 'user' group. These will be
 * combined with the permissions of all groups that a given user is listed
 * in in the user_groups table.
 *
 * Note: Don't set $wgGroupPermissions = array(); unless you know what you're
 * doing! This will wipe all permissions, and may mean that your users are
 * unable to perform certain essential tasks or access new functionality
 * when new permissions are introduced and default grants established.
 *
 * Functionality to make pages inaccessible has not been extensively tested
 * for security. Use at your own risk!
 *
 * This replaces wgWhitelistAccount and wgWhitelistEdit
 */
#$wgGroupPermissions = array();
$wgGroupPermissions['*']['read'] = false;
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['*']['move'] = false;
$wgGroupPermissions['*']['upload'] = false;
$wgGroupPermissions['*']['createpage'] = false;

$wgGroupPermissions['Users']['read'] = true;
$wgGroupPermissions['Users']['edit'] = true;
$wgGroupPermissions['Users']['createpage'] = true;
$wgGroupPermissions['Users']['move'] = true;
$wgGroupPermissions['Users']['upload'] = true;
$wgGroupPermissions['Users']['moveFile'] = true;



 
// // Implicit group for all logged-in accounts
// $wgGroupPermissions['user']['move']             = false;
// $wgGroupPermissions['user']['move-subpages']    = false;
// $wgGroupPermissions['user']['move-rootuserpages'] = false; // can move root userpages
// //$wgGroupPermissions['user']['movefile']         = true;	// Disabled for now due to possible bugs and security concerns
$wgGroupPermissions['user']['read']             = false;
// $wgGroupPermissions['user']['edit']             = false;
// $wgGroupPermissions['user']['createpage']       = false;
// $wgGroupPermissions['user']['createtalk']       = false;
// $wgGroupPermissions['user']['writeapi']         = false;
// $wgGroupPermissions['user']['upload']           = false;
// $wgGroupPermissions['user']['reupload']         = false;
// $wgGroupPermissions['user']['reupload-shared']  = false;
// $wgGroupPermissions['user']['minoredit']        = false;
// $wgGroupPermissions['user']['purge']            = false; // can use ?action=purge without clicking "ok"
 

// // Implicit group for all logged-in accounts
// $wgGroupPermissions['admin']['move']             = false;
// $wgGroupPermissions['admin']['move-subpages']    = false;
// $wgGroupPermissions['admin']['move-rootuserpages'] = false; // can move root userpages
// //$wgGroupPermissions['user']['movefile']         = true;	// Disabled for now due to possible bugs and security concerns
// $wgGroupPermissions['buerocrat']['read']             = true;
// $wgGroupPermissions['user']['edit']             = false;
// $wgGroupPermissions['user']['createpage']       = false;
// $wgGroupPermissions['user']['createtalk']       = false;
// $wgGroupPermissions['user']['writeapi']         = false;
// $wgGroupPermissions['user']['upload']           = false;
// $wgGroupPermissions['user']['reupload']         = false;
// $wgGroupPermissions['user']['reupload-shared']  = false;
// $wgGroupPermissions['user']['minoredit']        = false;
// $wgGroupPermissions['user']['purge']            = false; // can use ?action=purge without clicking "ok"
